name: publicreporting

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - publicreporting_network

networks:
  publicreporting_network:
    driver: bridge
    
volumes:
  minio_data:
    driver: local
